// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmv-Cl8j_7NWYrB8bBKwIty0PcTj1yazM',
    appId: '1:980313543309:web:3149fe9d640abe7c67c8c4',
    messagingSenderId: '980313543309',
    projectId: 'al-khalid',
    authDomain: 'al-khalid.firebaseapp.com',
    storageBucket: 'al-khalid.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM2MG6CbVq7SIzXt6AOrQi_FviebfSyks',
    appId: '1:980313543309:android:2aa715d66119b04767c8c4',
    messagingSenderId: '980313543309',
    projectId: 'al-khalid',
    storageBucket: 'al-khalid.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD272lOvPZw1Fv-BOvfzx7UZtqwLcCtMyg',
    appId: '1:980313543309:ios:2b97edcb2ee80e4b67c8c4',
    messagingSenderId: '980313543309',
    projectId: 'al-khalid',
    storageBucket: 'al-khalid.firebasestorage.app',
    iosClientId: '980313543309-lo2a1faagbbrr5l6oqgqdlbifltpgqen.apps.googleusercontent.com',
    iosBundleId: 'com.microstatik.alKhaliq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD272lOvPZw1Fv-BOvfzx7UZtqwLcCtMyg',
    appId: '1:980313543309:ios:2b97edcb2ee80e4b67c8c4',
    messagingSenderId: '980313543309',
    projectId: 'al-khalid',
    storageBucket: 'al-khalid.firebasestorage.app',
    iosClientId: '980313543309-lo2a1faagbbrr5l6oqgqdlbifltpgqen.apps.googleusercontent.com',
    iosBundleId: 'com.microstatik.alKhaliq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmv-Cl8j_7NWYrB8bBKwIty0PcTj1yazM',
    appId: '1:980313543309:web:37eda99bb5eadd2a67c8c4',
    messagingSenderId: '980313543309',
    projectId: 'al-khalid',
    authDomain: 'al-khalid.firebaseapp.com',
    storageBucket: 'al-khalid.firebasestorage.app',
  );
}
